all:
  hosts:
    k8s-master-01:
      ansible_host: 89.169.128.19
      ip: 10.10.1.11
      access_ip: 10.10.1.11
    k8s-worker-01:
      ansible_host: 89.169.173.194
      ip: 10.10.2.12
      access_ip: 10.10.2.12
    k8s-worker-02:
      ansible_host: 51.250.37.240
      ip: 10.10.3.13
      access_ip: 10.10.3.13
  children:
    kube_control_plane:
      hosts:
        k8s-master-01:
    kube_node:
      hosts:
        k8s-worker-01:
        k8s-worker-02:
    etcd:
      hosts:
        k8s-master-01:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
